name: Accessible Dialog
author: mashalla
category: Widget
tags: [dialog, tooltip, modal, window, alert, confirm]
#docs: http://ascribedata.com/moo/dialog/
demo: http://mashalla.github.com/dialog
current: 1.0